[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

upload_port  = /dev/cu.usbserial-3110
monitor_port = /dev/cu.usbserial-3110

; SPIFFS filesystem — stores index.html served to iPhone
board_build.filesystem = spiffs

; WebSocket library
lib_deps =
  links2004/WebSockets @ ^2.4.1
