[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Serial Monitor speed — must match the value in main.cpp
monitor_speed = 115200

; Upload speed
upload_speed = 921600

; Lock to the ESP32's USB port — no more Bluetooth guessing
upload_port  = /dev/cu.usbserial-3110
monitor_port = /dev/cu.usbserial-3110
